# Generated by Django 6.1 on 2026-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('x_twitter', 'X / Twitter'), ('x', 'X'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('website', 'Personal Website'), ('other', 'Other')], help_text='Social media platform or page type.', max_length=50)),
                ('link', models.URLField(help_text='The URL of the social profile or page.', max_length=500)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
